# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/book.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/book.proto\x12\x04\x62ook\x1a\x1egoogle/protobuf/wrappers.proto\"`\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04tags\x18\x02 \x03(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x0e\n\x06\x61uthor\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x64 \x01(\x03\"3\n\x07\x42ookSet\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1c\n\x08\x62ookList\x18\x03 \x03(\x0b\x32\n.book.Book2\xae\x02\n\x0b\x42ookService\x12\x33\n\x07\x61\x64\x64\x42ook\x12\n.book.Book\x1a\x1c.google.protobuf.StringValue\x12\x33\n\x07getBook\x12\x1c.google.protobuf.StringValue\x1a\n.book.Book\x12\x39\n\x0bsearchBooks\x12\x1c.google.protobuf.StringValue\x1a\n.book.Book0\x01\x12\x39\n\x0bupdateBooks\x12\n.book.Book\x1a\x1c.google.protobuf.StringValue(\x01\x12?\n\x0cprocessBooks\x12\x1c.google.protobuf.StringValue\x1a\r.book.BookSet(\x01\x30\x01\x42+\n\x15org.javaboy.grpc.demoB\x10\x42ookServiceProtoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.book_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025org.javaboy.grpc.demoB\020BookServiceProtoP\001'
  _BOOK._serialized_start=58
  _BOOK._serialized_end=154
  _BOOKSET._serialized_start=156
  _BOOKSET._serialized_end=207
  _BOOKSERVICE._serialized_start=210
  _BOOKSERVICE._serialized_end=512
# @@protoc_insertion_point(module_scope)
